// This file can be replaced during build by using the `fileReplacements` array.
// `ng build` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  production: true,
  version: env['npm_package_version'] + '-dev',
  serverUrl: '/api',
  defaultLanguage: 'es-ES',
  supportedLanguages: ['es-ES'],
  firebase: {
    apiKey: 'AIzaSyDXfMTMIJtARdUN1Dtax9_QFo3z0UwReLA',
    authDomain: 'pruebaangular-39655.firebaseapp.com',
    databaseURL: 'https://pruebaangular-39655-default-rtdb.firebaseio.com',
    projectId: 'pruebaangular-39655',
    storageBucket: 'pruebaangular-39655.appspot.com',
    messagingSenderId: '925273290737',
    appId: '1:925273290737:web:4573f2b7550243034eb650',
    measurementId: 'G-R1B2BQCQDB',
  },
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/plugins/zone-error';  // Included with Angular CLI.
